
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[267] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   68,   68,    0,    0,
        0,    0,    0,    0,   96,   95,   22,   23,   21,    1,
       95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   24,   38,   95,   35,   36,   30,   28,
       29,   37,   37,   37,   25,   25,   25,   25,   25,   95,
       39,   42,   95,   95,   95,   40,   43,   45,   95,   46,
       48,   47,   49,   51,   50,   52,   63,   95,   59,   60,
       58,   56,   61,   61,   61,   54,   54,   64,   67,   65,
       68,   69,   80,   79,   74,   75,   73,   72,   76,   78,

       78,   78,   94,   93,   86,   86,   89,   88,   92,   87,
       87,   90,   91,   84,   81,   82,    1,    0,    0,    0,
        0,    0,    0,    0,   15,    0,    0,    0,    0,    4,
        0,    0,    0,    0,    0,   26,   29,   37,   25,    0,
       25,    0,    0,   32,    0,   30,    0,   41,    0,   40,
       40,    0,    0,   47,   50,    0,   57,   56,   61,   54,
       55,    0,   54,    0,   65,    0,   65,   68,   72,   78,
        0,   78,    0,   71,   88,   87,   87,    0,   82,    0,
       82,    1,    3,    0,    7,   12,   20,    8,    0,    0,
        0,   10,    0,    2,    0,   17,    0,    0,    5,    0,

        0,   31,   34,   33,    0,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   85,    0,    0,    1,
       11,    0,   13,    0,    9,    0,    0,   18,    0,   27,
        0,    0,   44,    0,    0,   53,    0,   62,    0,   66,
        0,    0,   77,    0,   70,    0,   83,    0,   14,   16,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   19,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,    1,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,    1,   19,   20,
       21,   22,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   25,   25,   32,   33,   34,   35,   36,
       25,   37,   38,   39,   40,   25,   25,   41,   25,   25,
       42,    1,   43,   44,    1,    1,   45,   45,   45,   45,

       46,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[284] =
    {   0,
        0,   40,   81,    0,  128,  144,  160,    0,    2,    4,
        6,   12,  201,    0,  248,    0,  662,  661,  289,    0,
      338,    0,  385,    0,  663,  666,  666,  666,  666,  644,
      627,   22,  626,  624,  623,    5,  630,   13,  619,  618,
      627,  614,  617,  666,  666,  645,  666,  666,  666,  666,
      632,   25,  666,  628,  422,   47,  428,  434,  440,  604,
      666,  666,  641,    1,  628,  122,  666,  666,  635,  666,
      666,  626,  666,  666,  625,  666,  666,  636,  666,  666,
      666,  623,   29,  666,  619,  162,  452,  666,  666,  248,
        0,  666,  666,  666,  666,  666,  666,  621,  666,  385,

      459,  471,  666,  666,  666,  666,  666,  620,  666,  147,
      478,  666,  666,  666,  666,  483,  619,  610,  596,  606,
      600,  606,  594,   21,  666,  594,  590,  587,  588,  666,
      595,   31,  590,  587,  617,  616,  603,  666,  666,  616,
      128,  593,  579,  666,  580,  666,  610,  609,  596,  481,
      476,  160,    7,  595,  594,  605,  604,  591,  666,  666,
      666,  604,  256,  558,  666,  577,  391,    0,  559,  666,
      569,  397,  535,  666,  543,  666,  446,    0,  666,  555,
      502,  529,  666,  522,  666,  666,  666,  666,  499,  499,
      493,  666,  478,  666,  482,  666,  475,  464,  666,  480,

      256,  666,  666,  666,  456,  455,  135,  510,  430,  491,
      394,  403,  509,  397,  515,  361,  666,  387,  521,  666,
      666,  245,  666,  220,  666,  143,  144,  666,  526,  666,
      175,  527,  666,  250,  532,  666,  173,  666,  538,  666,
      172,  540,  666,  162,  666,  544,  666,  157,  666,  666,
      666,  117,  141,   10,  500,   62,   75,  461,   58,  546,
       57,  549,    9,  552,  666,  666,  563,  567,  571,  575,
      579,  583,  585,  587,  589,  591,    8,  593,  595,  597,
      599,  601,  603
    } ;

static const flex_int16_t yy_def[284] =
    {   0,
      267,  267,  266,    3,  267,  267,  267,    7,  267,  267,
      267,  267,  266,   13,  267,   15,  268,  268,  266,   19,
      266,   21,  267,   23,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  269,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  270,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  271,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      272,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  269,  269,  266,  266,  266,  273,
      266,  266,  266,  266,  266,  266,  270,  270,  266,  266,
      266,  266,  266,  266,  266,  271,  271,  266,  266,  266,
      266,  274,  266,  266,  266,  275,  266,  272,  266,  266,
      276,  266,  266,  266,  266,  266,  266,  277,  266,  278,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  273,

      273,  266,  266,  266,  266,  266,  266,  266,  274,  274,
      266,  275,  275,  276,  276,  266,  266,  278,  278,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      279,  266,  266,  266,  266,  266,  280,  266,  266,  266,
      281,  266,  266,  282,  266,  266,  266,  283,  266,  266,
      266,  266,  279,  279,  266,  266,  280,  280,  281,  281,
      282,  282,  283,  283,  266,    0,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266
    } ;

static const flex_int16_t yy_nxt[716] =
    {   0,
      266,   27,   28,   29,   70,   71,   70,   71,   73,   74,
      207,  217,  263,  266,   73,   74,  149,   30,  150,   72,
      230,   72,   31,   75,  208,   32,   33,   34,   35,   75,
       36,   37,  125,   38,   39,   40,   41,   42,  126,  128,
       43,   27,   28,   29,  119,  138,  138,  129,  120,  159,
      159,  139,  121,  139,  139,  139,  140,   30,  189,  190,
      261,  259,   31,  196,  141,   32,   33,   34,   35,  197,
       36,   37,  233,   38,   39,   40,   41,   42,  257,  256,
       43,   26,   26,   44,   45,   26,   46,   26,   26,   26,
       47,   48,   49,   49,   50,   49,   26,   49,   51,   50,

       52,   53,   54,   55,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   57,   58,   56,   56,   56,   56,
       56,   59,   47,   48,   26,   26,   26,   47,   60,   48,
       61,   62,  139,   63,  139,  139,  139,  149,  207,  150,
       64,   62,   64,   65,  253,   66,   61,   62,  152,   63,
      265,  176,  208,  176,  176,  176,   64,   62,   64,   65,
      263,   66,   67,   68,  177,  261,  160,  152,  160,  161,
      160,  162,  205,   68,  205,  259,  257,  206,  253,  163,
      252,  251,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   26,   26,   76,   77,   26,   78,   26,   26,   26,
       79,   80,   81,   81,   26,   81,   26,   81,   82,   26,
       83,   84,   85,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   86,   86,   86,   87,
       86,   86,   79,   80,   81,   26,   26,   79,   26,   80,
       88,   89,  165,  255,  165,  165,  165,  166,  250,  229,
      160,   89,  160,  161,  160,  167,  230,  256,  249,  231,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   26,
       26,   93,   94,   26,   26,   26,   26,   26,   95,   96,

       97,   97,   26,   97,   26,   97,   98,   26,   26,   99,
       26,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  101,  102,  100,  100,
       95,   96,   97,   26,   26,   95,   26,   96,   26,   26,
      103,  104,   26,   26,   26,   26,   26,  105,  106,  107,
      107,   26,  107,   26,  107,  108,   26,   26,  109,   26,
      110,  110,  110,  110,  110,  111,  110,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  112,
      113,  107,   26,   26,  112,   26,  113,  114,  115,  170,
      218,  170,  170,  170,  171,  165,  245,  165,  165,  165,

      214,  170,  172,  170,  170,  170,  212,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  116,  116,  116,  116,
      116,  116,  116,  116,  116,  116,  139,  238,  139,  139,
      139,  140,  139,  209,  139,  139,  139,  140,  139,  141,
      139,  139,  139,  140,  139,  141,  139,  139,  139,  140,
      176,  141,  176,  176,  176,  142,  160,  141,  160,  161,
      160,  162,  143,  170,  266,  170,  170,  170,  171,  163,
      144,  236,  206,  206,  145,  170,  172,  170,  170,  170,
      171,  164,  176,  200,  176,  176,  176,  179,  172,  179,
      179,  179,  180,  151,  235,  177,  149,  173,  150,  228,

      181,  236,  152,  255,  237,  174,  179,  152,  179,  179,
      179,  178,  239,  232,  227,  226,  225,  256,  242,  240,
      233,  152,  241,  234,  246,  243,  152,  208,  244,  229,
      232,  247,  224,  223,  248,  235,  230,  233,  222,  231,
      234,  239,  236,  242,  221,  237,  220,  246,  240,  266,
      243,  241,  266,  244,  247,  266,  240,  248,  218,  243,
      175,  216,  247,   26,   26,   26,   26,   91,   91,   91,
       91,  135,  214,  135,  135,  147,  169,  147,  147,  156,
      212,  156,  156,  168,  211,  168,  168,  201,  201,  210,
      210,  213,  213,  215,  215,  219,  219,  254,  254,  258,

      258,  260,  260,  262,  262,  264,  264,  209,  158,  157,
      157,  155,  154,  151,  148,  148,  204,  203,  202,  200,
      137,  136,  136,  199,  198,  195,  194,  193,  192,  191,
      188,  187,  186,  185,  184,  183,  182,  175,  169,  159,
      158,  157,  155,  154,  153,  151,  148,  146,  138,  137,
      136,  134,  133,  132,  131,  130,  127,  124,  123,  122,
      118,  117,  266,   92,   92,   25,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266
    } ;

static const flex_int16_t yy_chk[716] =
    {   0,
        0,    1,    1,    1,    9,    9,   10,   10,   11,   11,
      153,  277,  263,  254,   12,   12,   64,    1,   64,    9,
      254,   10,    1,   11,  153,    1,    1,    1,    1,   12,
        1,    1,   36,    1,    1,    1,    1,    1,   36,   38,
        1,    2,    2,    2,   32,   52,   52,   38,   32,   83,
       83,   56,   32,   56,   56,   56,   56,    2,  124,  124,
      261,  259,    2,  132,   56,    2,    2,    2,    2,  132,
        2,    2,  256,    2,    2,    2,    2,    2,  257,  256,
        2,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        5,    5,  141,    5,  141,  141,  141,   66,  207,   66,
        5,    5,    5,    5,  253,    5,    6,    6,   66,    6,
      252,  110,  207,  110,  110,  110,    6,    6,    6,    6,
      248,    6,    7,    7,  110,  244,   86,   66,   86,   86,
       86,   86,  152,    7,  152,  241,  237,  152,  231,   86,
      227,  226,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       15,   15,   90,  234,   90,   90,   90,   90,  224,  201,
      163,   15,  163,  163,  163,   90,  201,  234,  222,  201,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   23,   23,  100,
      218,  100,  100,  100,  100,  167,  216,  167,  167,  167,

      214,  172,  100,  172,  172,  172,  212,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   55,  211,   55,   55,
       55,   55,   57,  209,   57,   57,   57,   57,   58,   55,
       58,   58,   58,   58,   59,   57,   59,   59,   59,   59,
      177,   58,  177,  177,  177,   55,   87,   59,   87,   87,
       87,   87,   57,  101,  258,  101,  101,  101,  101,   87,
       58,  258,  206,  205,   59,  102,  101,  102,  102,  102,
      102,   87,  111,  200,  111,  111,  111,  116,  102,  116,
      116,  116,  116,  151,  210,  111,  150,  101,  150,  198,

      116,  210,  151,  255,  210,  102,  181,  150,  181,  181,
      181,  111,  213,  208,  197,  195,  193,  255,  215,  213,
      208,  151,  213,  208,  219,  215,  150,  208,  215,  229,
      232,  219,  191,  190,  219,  235,  229,  232,  189,  229,
      232,  239,  235,  242,  184,  235,  182,  246,  239,  260,
      242,  239,  262,  242,  246,  264,  260,  246,  180,  262,
      175,  173,  264,  267,  267,  267,  267,  268,  268,  268,
      268,  269,  171,  269,  269,  270,  169,  270,  270,  271,
      166,  271,  271,  272,  164,  272,  272,  273,  273,  274,
      274,  275,  275,  276,  276,  278,  278,  279,  279,  280,

      280,  281,  281,  282,  282,  283,  283,  162,  158,  157,
      156,  155,  154,  149,  148,  147,  145,  143,  142,  140,
      137,  136,  135,  134,  133,  131,  129,  128,  127,  126,
      123,  122,  121,  120,  119,  118,  117,  108,   98,   85,
       82,   78,   75,   72,   69,   65,   63,   60,   54,   51,
       46,   43,   42,   41,   40,   39,   37,   35,   34,   33,
       31,   30,   25,   18,   17,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[96] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "BMM_Scanner.l"
#line 2 "BMM_Scanner.l"

/* This is the C code for including header file and declaring Variables */

#include <stdio.h>
#include <string.h>
#include "y.tab.h"
extern int yylval;
extern void yyerror(const char* message);
int forCounter=0;
int gosubCounter=0;
int endCounter = 0;
void yyerror(const char* message);

int countn=0;


int foo(long long yyleng, char *yytext);
void LETStatement(char* yytext, long long yyleng);
void PRINTStatement(char* yytext, long long yyleng);
#line 737 "lex.yy.c"
/* Remaining --> DATA?, DEF, DIM, FOR, GOTO, GOSUB, IF, INPUT */
/* REM -> 0*/
/* STOP -> 1*/

/* Left--> variable type error, print error (I, negative consideration in NUM I=-1  */
#line 743 "lex.yy.c"

#define INITIAL 0
#define expression 1
#define value 2
#define dim 3
#define gotoo 4
#define gosub 5
#define iff 6
#define inputt 7
#define remm 8
#define forr 9
#define deff 10
#define nextt 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "BMM_Scanner.l"


#line 974 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 666 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "BMM_Scanner.l"
{yylval=atoi(yytext); return ID;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 49 "BMM_Scanner.l"
{return NOT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "BMM_Scanner.l"
{return AND;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "BMM_Scanner.l"
{return OR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "BMM_Scanner.l"
{return XOR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "BMM_Scanner.l"
{BEGIN(expression); fprintf(yyout,"PRINT Statement found!\n"); return PRINT;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "BMM_Scanner.l"
{BEGIN(deff); fprintf(yyout,"DEF Statement found!\n"); return DEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "BMM_Scanner.l"
{forCounter++;BEGIN(forr); fprintf(yyout,"FOR Statement found!\n"); return FOR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "BMM_Scanner.l"
{
                forCounter--; 
                BEGIN(nextt); 
                fprintf(yyout,"NEXT Statement found!\n"); return NEXT;
                if(forCounter%2!=0){
                    fprintf(yyout,"ERROR: NEXT STATEMENT AND FOR DO NOT MATCH, EXITING\n");
                }
            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 64 "BMM_Scanner.l"
{BEGIN(expression); fprintf(yyout,"LET Statement found!\n"); return LET;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 65 "BMM_Scanner.l"
{BEGIN(value); fprintf(yyout,"DATA Statement found!\n"); return DATA;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 66 "BMM_Scanner.l"
{BEGIN(dim); fprintf(yyout,"DIM Statement found!\n"); return DIM;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "BMM_Scanner.l"
{BEGIN(gotoo); fprintf(yyout,"GOTO Statement found!\n"); return GOTO;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 68 "BMM_Scanner.l"
{gosubCounter++;BEGIN(gosub); fprintf(yyout,"GOSUB Statement found!\n"); return GOSUB;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 69 "BMM_Scanner.l"
{BEGIN(iff); fprintf(yyout,"IF Statement found!\n"); return IF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 70 "BMM_Scanner.l"
{BEGIN(inputt); fprintf(yyout,"INPUT Statement found!\n"); return INPUT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 71 "BMM_Scanner.l"
{BEGIN(remm); fprintf(yyout,"REM Statement found! Comment\n"); return REM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 72 "BMM_Scanner.l"
{fprintf(yyout,"STOP Statement found!\n"); return STOP;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "BMM_Scanner.l"
{
                gosubCounter--;
                fprintf(yyout,"RETURN Statement found!\n");
                if(gosubCounter%2!=0){
                    fprintf(yyout,"ERROR: RETURN STATEMENT AND GOSUB DO NOT MATCH, EXITING \n");
                } 
                return RETURN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "BMM_Scanner.l"
{
                fprintf(yyout,"END Statement found!\n"); 
                endCounter++;
                if(endCounter>1){
                    yyerror("INVALID:END OCCURED MORE THAN ONCE\n");
                    exit(0);
                } 
                return END;
            }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "BMM_Scanner.l"
{;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "BMM_Scanner.l"
{fprintf(yyout,"Syntax Error: Tabs are not allowed\n");}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 91 "BMM_Scanner.l"
{ countn++; fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(expression):
case YY_STATE_EOF(value):
case YY_STATE_EOF(dim):
case YY_STATE_EOF(gotoo):
case YY_STATE_EOF(gosub):
case YY_STATE_EOF(iff):
case YY_STATE_EOF(inputt):
case YY_STATE_EOF(remm):
case YY_STATE_EOF(forr):
case YY_STATE_EOF(deff):
case YY_STATE_EOF(nextt):
#line 92 "BMM_Scanner.l"
{fprintf(yyout,"Program Checked Successfully!!!\n");exit(0);}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 94 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 95 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 96 "BMM_Scanner.l"
{return STRING;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 97 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 98 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 99 "BMM_Scanner.l"
{return NUM;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 100 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 101 "BMM_Scanner.l"
{return AND;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 102 "BMM_Scanner.l"
{return OR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 103 "BMM_Scanner.l"
{return XOR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 104 "BMM_Scanner.l"
{return NOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 110 "BMM_Scanner.l"

	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 113 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "BMM_Scanner.l"
{return FLOAT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "BMM_Scanner.l"
{return STRING;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "BMM_Scanner.l"

	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 119 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 120 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return DIMDATA;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 121 "BMM_Scanner.l"

	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 123 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "BMM_Scanner.l"
{fprintf(yyout,"Line to GOTO: %s\n", yytext);return GOTOID;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "BMM_Scanner.l"

	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 127 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 128 "BMM_Scanner.l"
{return GOSUBID;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 129 "BMM_Scanner.l"

	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 131 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 133 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return IFVAR;/*DIMDATA VARIABLE*/}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 134 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return IFVAR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 135 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return IFSTRINGVAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 136 "BMM_Scanner.l"
{return IFNUM;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 137 "BMM_Scanner.l"
{return IFSTRING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 139 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 140 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 141 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 142 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 144 "BMM_Scanner.l"
{return THEN;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 146 "BMM_Scanner.l"

	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 148 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 149 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s\n", yytext);return INPUTTOKEN;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 150 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s\n", yytext);return INPUTTOKEN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 151 "BMM_Scanner.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 153 "BMM_Scanner.l"
{}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 154 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 156 "BMM_Scanner.l"
{return STEP;/*STEP detected*/}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 157 "BMM_Scanner.l"
{return TO;/*TO detected*/}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 159 "BMM_Scanner.l"
{return NUM;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 160 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 161 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 162 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 163 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 165 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 166 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 167 "BMM_Scanner.l"
{/*space detected*/}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 168 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 171 "BMM_Scanner.l"
{/*space detected*/}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 172 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 173 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 174 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 177 "BMM_Scanner.l"
{return FN;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 178 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 179 "BMM_Scanner.l"
{fprintf(yyout,"Identifier: %s \n", yytext);return VAR;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 180 "BMM_Scanner.l"
{return NUM;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 181 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 182 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 183 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 184 "BMM_Scanner.l"
{return yytext[0];}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 185 "BMM_Scanner.l"

	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 187 "BMM_Scanner.l"
{BEGIN(0);fprintf(yyout,"------------------------------------------------------\n");}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 189 "BMM_Scanner.l"
ECHO;
	YY_BREAK
#line 1564 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 266);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 189 "BMM_Scanner.l"




int foo(long long yyleng, char *yytext)
{
    fprintf(yyout,"yyleng: %lld\n", yyleng);
    for (int i = 0; i < yyleng; i++)
    {
        fprintf(yyout,"%c", yytext[i]);
    }
    return yyleng;
}

void LETStatement(char* yytext, long long yyleng)
{
    fprintf(yyout,"LET statement found\n");
    // Parse LET Statement and return the token
    char* token = strtok(yytext, " ");
    char* variable = strtok(NULL, " ");
    char* operator = strtok(NULL, "=");
    char* operand = strtok(NULL, " ");
    fprintf(yyout,"Token: %s\n", token);
    fprintf(yyout,"Variable: %s\n", variable);
    fprintf(yyout,"Operator: %s\n", operator);
    fprintf(yyout,"Operand: %s\n", operand);

}

void PRINTStatement(char* yytext, long long yyleng)
{
    fprintf(yyout,"PRINT statement found\n");
    // Parse PRINT Statement and return the token
    char* token = strtok(yytext, " ");
    char* variable = strtok(NULL, " ");
    char* operator = strtok(NULL, " ");
    fprintf(yyout,"Token: %s\n", token);
    fprintf(yyout,"Variable: %s\n", variable);
    fprintf(yyout,"Operator: %s\n", operator);
}

int yywrap()
{
    return 1;
}

